### ISSUE TITLE
docker squash fails on OSX - "This does not look like a tar archive"

### ISSUE THREAD

**Issue by alanruttenberg** [jwilder/docker-squash#75] opened 2017-09-15 20:03 UTC
I'm running

    docker save fd12f21eddf6 | sudo ./docker-squash -t squash -verbose | docker load

I installed gnu tar with brew as without that I get: 

    tar: Option --xattrs is not supported

To be absolutely sure it's used I moved it on top of /usr/bin/tar

I'm running 10.10.5 (Yosemite) and the latest Docker for Mac (Version 17.06.2-ce-mac27 (19124) Channel: stable 428bd6ceae)
 
Here's the output.

    Loading export from STDIN using /tmp/docker-squash987645616 for tempdir
    Loaded image w/ 30 layers
    Extracting layers...
      -  /tmp/docker-squash987645616/1b05ab0e9bd8d980c8aa8968d19aa68627f8c338f681544c3010f0bfd957e6ca/layer.tar
      -  /tmp/docker-squash987645616/ec07124dd80e200976071de65833378075aada1d0adab8456efccce9bbf022b4/layer.tar
      -  /tmp/docker-squash987645616/142f88c4666ac1bc0ba66ad3d630b8ef59e58ccc0dccfc372f623cd87792323b/layer.tar
      -  /tmp/docker-squash987645616/f47a45017ff545a742662efee70dbef3313b376d2dddfb567d6865998b36086d/layer.tar
      -  /tmp/docker-squash987645616/febf9a1fe421e1b47947056600d37a5ad2b622c29bed9c96a564d291c50324c2/layer.tar
      -  /tmp/docker-squash987645616/51d6d007242ca0257d680b2a36043bc7746bc0804520214b2b2a5963ea9f2f41/layer.tar
      -  /tmp/docker-squash987645616/a2f3950abcd0ce8c206f8b4d5c9241755eb90b2cc8e601bd0d315c0188457ad4/layer.tar
      -  /tmp/docker-squash987645616/f291282e62ec1dba277c9506d4df557c25423a7f76a7f9a251754d666f64c85e/layer.tar
      -  /tmp/docker-squash987645616/05651b4024f34a1a2c5ca6a0a7e9f24be7e9ad161b510d5d1e39edb3a27f7d5a/layer.tar
      -  /tmp/docker-squash987645616/1fe21dca27267ff71fd4f6b3b3d988635080b1bb6da6942d9081081974588e7c/layer.tar
      -  /tmp/docker-squash987645616/70bbb368f49a0c3d49a3455bcc595283850ab8c81d0cbb33e5f992f2bb99f764/layer.tar
      -  /tmp/docker-squash987645616/814e026ee3b455f905e25e52079508c49653d59ecce264286ff75b90c0835601/layer.tar
      -  /tmp/docker-squash987645616/16c2e7f2d8f2fcbd002904ad11e590c72db2504e0ee80e52abe37dfd87c450c0/layer.tar
      -  /tmp/docker-squash987645616/76f11833eadf6906e817697cce21619eaa9ad5f04f228684186d814062cca915/layer.tar
      -  /tmp/docker-squash987645616/accfc3047062753cb1727137e0ec28042aee861314aa988c135082fb67ab3ad1/layer.tar
      -  /tmp/docker-squash987645616/61fddb9fcc41e2cfba46b9240f787591e4e9b4c5afe839c5d9b95e9b2b6d2752/layer.tar
      -  /tmp/docker-squash987645616/4e24aea5132c2a695e6c31d70e3f45c18995c724043251d722b0aef45e23b080/layer.tar
      -  /tmp/docker-squash987645616/6a26c279dcd43d6562be3d8ece9260b038a7d5fc1c3d067487bef02a9ec75978/layer.tar
      -  /tmp/docker-squash987645616/6bbf7225ee4fa10e7eb5e720a861da46ddb2eb1bfe89b6aaa43e19ad91843f10/layer.tar
      -  /tmp/docker-squash987645616/98977e8b662352a200b2c0a05d26cf0ea341eb61153b549b5c6eabed3d4922d7/layer.tar
      -  /tmp/docker-squash987645616/1ae165074fc962fd56c735517233c6ed21cd68ddeacfa45f7364c1e3b137bf26/layer.tar
      -  /tmp/docker-squash987645616/2cef90908282520fb63ece09db899f67fa74f2cf2154834a54d409f55d6835b3/layer.tar
      -  /tmp/docker-squash987645616/36205cdc27f4c0b09a5181d65eac611d5ac88932b9d680de5f43819def949cb6/layer.tar
      -  /tmp/docker-squash987645616/8ab9aa6f4cb380e1f881bd5b9bd0f2ec3a4bcfe22d3719a530fb4f20ac8f491f/layer.tar
      -  /tmp/docker-squash987645616/9f0dd5ad0a03bc166480b6345022fbf5dc84fecf12a79eed75dec3ff5f787424/layer.tar
      -  /tmp/docker-squash987645616/fd3ed0ce999cf742424de54db2e46b094742f8fbed6fdbbcda2d702d993a8d91/layer.tar
      -  /tmp/docker-squash987645616/22a597662d30247d0537def9164860e04fa091acea590a89dc428d5f28218c92/layer.tar
      -  /tmp/docker-squash987645616/c17694d7087b887bd6fbbab95c541cfb03632ba2939d7267ee41e069dfed3aa4/layer.tar
      -  /tmp/docker-squash987645616/cf980b1deb433f0fab37ebbc9c48f67d34eaa659ae1bc6f50a3441adeade084d/layer.tar
    tar: This does not look like a tar archive
    tar: Exiting with failure status due to previous errors

    ERROR: exit status 2
    Removing tempdir /tmp/docker-squash987645616
    open /var/lib/docker/tmp/docker-import-079718931/repositories: no such file or directory

**Comment by alanruttenberg** [comment] 2017-09-15 20:31
Found --squash parameter to docker build, so more FYI at this point.

A bit more info. I tried to run docker-squash on that docker --squashed image and it did not error out, and output ended with

    Loaded image ID: sha256:da0602ba7090f278722bd45541247b1b7af0bf1c59b57c0e0fd64b709db72bde

However it does not seem to have registered the new image - I don't see the tag when I run docker images, and the docker --squashed image still has has 6 layers in it's docker saved tar file.  The ID given in that output is the same as that of the original.

**Comment by ggoetz-hyperion** [comment] 2018-01-30 19:18
For me, this was caused by a symlink. I extracted the tar myself and found:
```
$ ls -hog */layer.tar
-rw-r--r-- 1 861M Dec  8 11:59 183b6ece9755494397a57fcac42bfb5040b94fd171094e6134c488c9a31becd5/layer.tar
-rw-r--r-- 1 3.0K Dec  8 11:59 24a7c82a953cdd6859e07db30e9898068de8c41c344a820ad3300a91f96934a3/layer.tar
-rw-r--r-- 1 8.7M Dec  8 11:59 275b9bc404b11ee062374a82b1e9c83e670c8b38b108e17357308dfe78731132/layer.tar
-rw-r--r-- 1  15K Dec  8 11:59 5674ec0eea4028541ffb7e1d183a2655136874d0217731d7fea755d274f7dd19/layer.tar
-rw-r--r-- 1 631M Dec  8 11:59 6585e05d2486563cca78b4b29cc3d29836210bd4dbf9f0a6cc708740827aa6fa/layer.tar
-rw-r--r-- 1 3.0K Dec  8 11:59 6c8a15b82688c314b400635a68fb39b9689b8c3009ff4010106277d3e1e24f52/layer.tar
-rw-r--r-- 1 5.5K Dec  8 11:59 76304a32289e01377cf6b4473a505f20614d0dde24a8f1f2e59a848477c42029/layer.tar
-rw-r--r-- 1 121M Dec  8 11:59 85e1f6191387bfb16ba74078b5ae0f99cf6a092bdcf05f9334fe2476b8cb08bf/layer.tar
-rw-r--r-- 1  31K Dec  8 11:59 a39253e421bbf3ba702e2d6cd59e02c2c8f657d793a1b68abd71ad5c63bca471/layer.tar
-rw-r--r-- 1  16K Dec  8 11:59 a7a03ad9aff62734fb75de249e853be7e87338b0b0877a505fb42665c9ffce7d/layer.tar
-rw-r--r-- 1 3.0K Dec  8 11:59 ee364bc6a066c5c29bd766b81a4862a88f724d4fc7bc12c3726a24d579e8c93c/layer.tar
lrwxrwxrwx 1   77 Jan 30 10:04 f66bb8a0c571e8e16f86454ce28fe289bce2ec25b13ea25150be440e4000f72b/layer.tar -> ../275b9bc404b11ee062374a82b1e9c83e670c8b38b108e17357308dfe78731132/layer.tar
```
Fixed with:
```diff
diff --git a/export.go b/export.go
index 23ae412..7f23257 100644
--- a/export.go
+++ b/export.go
@@ -229,6 +229,13 @@ func (e *Export) Extract(r io.Reader) error {

                        continue
                }
+               if header.Typeflag == tar.TypeSymlink {
+                       err = os.Symlink(header.Linkname, fn)
+                       if err != nil {
+                               return err
+                       }
+                       continue
+               }

                item, err := os.OpenFile(fn, os.O_CREATE|os.O_WRONLY, header.FileInfo().Mode())
                if err != nil {
```

**Closed** 2021-05-21 22:44 UTC
