### ISSUE TITLE
Fails on squashed.tar loading

### ISSUE THREAD

**Issue by Somebi** [jwilder/docker-squash#49] opened 2016-03-04 13:34 UTC
$ docker save <image id> > image.tar
$ sudo docker-squash -i image.tar -o squashed.tar -t newtag
$ cat squashed.tar | docker load
$ docker images <new image id>

Fails silently after doing cat squashed.tar | docker load. Image therefore is not in the list of images.

Docker version 1.10.0, build 590d5108

**Comment by jwilder** [comment] 2016-03-04 15:53
Duplicate of #45.  Docker 1.10 doesn't work with `docker-squash` currently due to the change in image formats to use content addressable ids.

**Closed by jwilder** 2016-03-04 15:53 UTC
